---
    version: '3'
    

    services:
        api:
            build: api
            environment:
                - IP=172.2.1.2
            networks:
                group1:
                    ipv4_address: 172.2.1.2
            ports:
                - "5000:5000"
                - "201:22"


        loadbalancer: 
            build: loadbalancer
            ports:
                - "8080:8080"
                - "203:22"
            networks:
                group1:
                    ipv4_address: 172.2.1.3
  
                    
        client:
            build: client
            environment:
                - LB_IP=172.2.1.3
            ports:
                - "202:22"
            networks:
                group1:
                    ipv4_address: 172.2.1.4

  
                    
    networks:
        group1:
            ipam:
                driver: default
                config:
                    - subnet: 172.2.0.0/16