---
    version: '3'
    

    services:
        api:
            build: api
            environment:
                - IP=172.2.1.2
            volumes:
                - ./api/:/var/project/api/

            networks:
                group1:
                    ipv4_address: 172.2.1.2
            ports:
                - "5000:5000"
                - "201:22"


        loadbalancer: 
            image: opentracing/nginx-opentracing
            ports:
                - "8080:8080"
                - "203:22"
            volumes:
                - ./loadbalancer/api.conf:/etc/nginx/nginx.conf
                - ./loadbalancer/jaeger-config.json:/etc/jaeger-config.json

            networks:
                group1:
                    ipv4_address: 172.2.1.3
  
                    
        client:
            build: client
            environment:
                - LB_IP=172.2.1.3
            ports:
                - "202:22"
            networks:
                group1:
                    ipv4_address: 172.2.1.4

        jaeger:
            image: jaegertracing/all-in-one
            environment:
                - COLLECTOR_ZIPKIN_HTTP_PORT=9411

            networks:
                group1:
                    ipv4_address: 172.2.1.5
                    #this ip is hardcoded in api code
            expose:
                - "9411"
                - "16686"
            ports:
                - "9411:9411"
                - "16686:16686"

  
                    
    networks:
        group1:
            ipam:
                driver: default
                config:
                    - subnet: 172.2.0.0/16